- name: xquartz のインストール (for Ricty)
  homebrew_cask: name=xquartz
- name: fontforge のインストール (for Ricty)
  homebrew: name=fontforge
- name: Ricty のインストール
  homebrew: name=ricty
- name: 生成されたフォントファイルをコピー
  shell: cp -f $(brew --cellar ricty)/*/share/fonts/Ricty*.ttf ~/Library/Fonts/
  args:
    creates: ~/Library/Fonts/Ricty-Bold.ttf
  notify: run fc-cache
