homebrew_taps:
  - homebrew/binary
  - homebrew/dupes
  - caskroom/cask
  - railwaycat/emacsmacport
  - sanemat/font
homebrew_packages:
  - { name: readline }
  - { name: openssl }
  - { name: openssl, state: linked, install_options: force }
  - { name: python }
  - { name: ansible }
  - { name: coreutils }
  - { name: git }
  - { name: zsh, install_options: disable-etcdir }
  - { name: wget }
  - { name: curl }
  - { name: cmake }
  - { name: autoconf }
  - { name: automake }
  - { name: pkg-config }
  - { name: ctags }
  - { name: tree }
  - { name: lv }
  - { name: nkf }
  - { name: jq }
  - { name: go }
  - { name: direnv }
  - { name: peco }
  - { name: hub }
  - { name: tig }
  - { name: rbenv }
  - { name: ruby-build }
  - { name: lha }
  - { name: mysql }
  - { name: sqlite }
  - { name: redis }
  - { name: xz }
  - { name: socat }
  - { name: rlwrap }
  - { name: autojump }
  - { name: gibo }
  - { name: source-highlight }
  - { name: nodebrew }
